### ISSUE TITLE
TestFairy SDK not approved by iTunes Connect automatic approval process

### ISSUE THREAD

**Issue by JagCesar** [testfairy/testfairy-carthage#3]
Hey!

I'm not sure if your SDK is supposed to be used in production or not, if the answer is no this issue can be closed.

If this SDK is supposed to be used in production you have to fix a thing that blocks apps using this SDK from being processed by Apple.

It's not allowed to have bash files in an app, and your `.framework` folder that is created by Carthage contains a bash file.

I know this bash file contains the script to upload dSYMs to your backend, but you will have to get rid of it from the compiled framework file. Maybe just have it in the repo, but not in the target, so it ends up in `Carthage/Checkouts/testfairy-carthage`?

Keep up the good work.

/C

**Comment by gmegidish** [comment]
Thanks for the update, this has been fixed and the script has build removed from the xcodeproj file.
